services:
  jouerflux:
    build: .
    container_name: jouerflux
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - .:/app